// This file was generated by RedwoodJS
import FatalErrorPageType from '/home/abr/perso/Projects/zefo/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/home/abr/perso/Projects/zefo/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/home/abr/perso/Projects/zefo/web/src/pages/HomePage/HomePage'
import LoginPageType from '/home/abr/perso/Projects/zefo/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/home/abr/perso/Projects/zefo/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/home/abr/perso/Projects/zefo/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/home/abr/perso/Projects/zefo/web/src/pages/SignupPage/SignupPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
}
