// This file was generated by RedwoodJS
import FatalErrorPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/HomePage/HomePage'
import LoginPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/Users/aloysberger/Documents/Projects/zefo/web/src/pages/SignupPage/SignupPage'

declare global {
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
}
