export const brands = [
  'Advance',
  'Aéros',
  'AirCross',
  'AirDesign',
  'Air-Sport',
  'Airwave',
  'Apco',
  'Axis',
  'Bruce Goldsmith Design - BGD',
  'Dudek',
  'Element',
  'Firebird',
  'Flying-Planet',
  'Gin',
  'Gradient',
  'Icaro',
  'Independence',
  'MacPara',
  'Mcc-Aviation',
  'Nervures',
  'Niviuk ',
  'Nova',
  'Ozone',
  'ParaAvis',
  'Paratech',
  'PPG Korea',
  'Pro-Design',
  'Sky',
  'Sky-Country',
  'Skywalk',
  'Sol',
  'Sun-Gliders',
  'Swing',
  'Trekking',
  '777 TripleSeven',
  'UP International',
  'U-Turn',
  'Windtech',
  'Skyman',
] as const

export const categories = ['wing', 'harness', 'rescue']
