name: 'Redwood Build, Lint, Diagnostics, and Tests'

run-name: 'Run CI on a Redwood Project'
on:  
  pull_request:
    branches:
     - main
  workflow_dispatch:
jobs:
  Premerge:
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: yarn install --immutable
        shell: bash

      - name: Run Build
        run: yarn rw build
        shell: bash

      - name: Run Lint
        run: yarn rw lint
        shell: bash

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn rw test
        shell: bash
